BEGIN;

ALTER TABLE chain_configs
  ADD COLUMN IF NOT EXISTS min_span INTEGER NOT NULL DEFAULT 8 CHECK (min_span > 0),
  ADD COLUMN IF NOT EXISTS max_span INTEGER NOT NULL DEFAULT 1000 CHECK (max_span >= min_span),
  ADD COLUMN IF NOT EXISTS start_block BIGINT,
  ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';

COMMIT;
