name: Collect Worker Logs

on:
  workflow_dispatch:
    inputs:
      env:
        description: "GitHub Environment"
        required: true
        default: production
      lines:
        description: "Lines per unit"
        required: true
        default: "400"

jobs:
  collect:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Assert environment bindings (presence only)
  shell: bash
  env:
    # REQUIRED
    SSH_HOST: ${{ secrets.SSH_HOST }}
    SSH_USER: ${{ secrets.SSH_USER }}
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    # OPTIONAL
    SSH_PORT: ${{ secrets.SSH_PORT }}
  run: |
    set +u

    missing_required=0

    check_required () {
      local k="$1"
      local v="${!k-}"
      if [ -n "$v" ]; then
        echo "::notice title=REQUIRED:$k::SET"
      else
        echo "::error title=REQUIRED:$k::MISSING"
        missing_required=1
      fi
    }

    check_optional () {
      local k="$1"
      local v="${!k-}"
      if [ -n "$v" ]; then
        echo "::notice title=OPTIONAL:$k::SET"
      else
        echo "::notice title=OPTIONAL:$k::MISSING (will not fail the job)"
      fi
    }

    echo "Asserting Environment: ${{ inputs.env }}"
    # Required
    check_required SSH_HOST
    check_required SSH_USER
    check_required SSH_PRIVATE_KEY

    # Optional
    check_optional SSH_PORT

    if [ "$missing_required" -ne 0 ]; then
      echo "One or more REQUIRED secrets are missing. Add them in Settings → Environments → ${{ inputs.env }}."
      exit 1
    fi


      - name: SSH: dump worker logs to files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT != '' && secrets.SSH_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 15m
          script: |
            set -euo pipefail
            LINES="${{ inputs.lines }}"
            OUTDIR="$HOME/worker-logs"
            rm -rf "$OUTDIR" && mkdir -p "$OUTDIR"

            systemctl list-units 'explorertoken-chain@*.service' --no-legend --no-pager \
              | awk '{print $1}' | sed 's/.service$//' \
              | while read -r unit; do
                  echo "Collecting $unit ..."
                  journalctl -u "$unit" -n "$LINES" --no-pager > "$OUTDIR/${unit}.log" || true
                done

            ls -la "$OUTDIR"

      - name: SCP: retrieve logs
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT != '' && secrets.SSH_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "worker-logs/*"
          target: "./"

      - name: Upload logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: worker-logs
          path: worker-logs
