name: Deploy to VPS

on:
  workflow_dispatch:
    inputs:
      env:
        description: "GitHub Environment"
        required: true
        default: production
      branch:
        description: "Branch to deploy"
        required: true
        default: main
      publish_dir:
        description: "Frontend publish directory on server (default: /var/www/html)"
        required: false
        default: ""

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Assert required secrets (presence only)
        shell: bash
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          set +u
          miss=0
          for k in SSH_HOST SSH_USER SSH_PRIVATE_KEY; do
            v="${!k-}"
            if [ -z "$v" ]; then
              echo "::error title=REQUIRED:$k::MISSING"
              miss=1
            else
              echo "::notice title=REQUIRED:$k::SET"
            fi
          done
          [ "$miss" -eq 0 ] || exit 1

      - name: Deploy over SSH (NVM-safe, preflight sudo, temp-clone + rsync, write systemd override)
        uses: appleboy/ssh-action@v1.0.3
        env:
          # Optional if NOPASSWD isn't configured
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}

          # Server locations (your current layout)
          BACKEND_DIR: /home/deploy/ExplorerToken/backend
          FRONTEND_DIR: /home/deploy/ExplorerToken/frontend
          REPO_URL: https://github.com/WickedBroX/Blockchain.git

          # FE publish directory (domain-agnostic). Blank → /var/www/html
          PUBLISH_DIR: ${{ inputs.publish_dir }}

          # Backend start specifics you confirmed
          NODE_BIN: /home/deploy/.nvm/versions/node/v22.21.0/bin/node
          ENTRYPOINT: dist/src/index.js
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 45m
          envs: SUDO_PASSWORD,BACKEND_DIR,FRONTEND_DIR,REPO_URL,PUBLISH_DIR,NODE_BIN,ENTRYPOINT
          script: |
            set -euo pipefail
            BRANCH="${{ inputs.branch }}"

            # ---------- helpers ----------
            log() { echo "[$(date +'%F %T')] $*"; }
            diag_dump() {
              echo "===== DEPLOY DIAGNOSTICS ====="
              date
              echo "User: $(whoami)"; echo "Host: $(hostname)"; echo "PWD: $(pwd)"
              echo "PATH: $PATH"
              echo "Node: $(command -v node || echo 'node not found')"
              node -v || true; npm -v || true
              echo; echo "== Backend dist =="; ls -la "$BACKEND_DIR/dist" || true
              echo; echo "== Unit file ==";  systemctl cat explorertoken-backend 2>&1 || true
              echo; echo "== Status ==";     systemctl status explorertoken-backend 2>&1 || true
              echo; echo "== Journal -xeu (tail 400) =="; journalctl -xeu explorertoken-backend 2>&1 | tail -n 400 || true
              echo; echo "== Journal -u (last 400) ==";  journalctl -u explorertoken-backend -n 400 --no-pager 2>&1 || true
              echo "===== END DIAGNOSTICS ====="
            }

            # ---------- sudo strategy ----------
            if [ -n "${SUDO_PASSWORD:-}" ]; then
              SUDO='sudo -S -p ""'
              echo "$SUDO_PASSWORD" | $SUDO -k true >/dev/null 2>&1 || { echo "ERROR: Invalid SUDO_PASSWORD or sudo not permitted."; diag_dump; exit 1; }
              run_sudo() { echo "$SUDO_PASSWORD" | $SUDO "$@"; }
            else
              if ! sudo -n true >/dev/null 2>&1; then
                echo "ERROR: sudo requires a password but SUDO_PASSWORD is not set."
                echo "Fix: add SUDO_PASSWORD in Environment 'production' or grant NOPASSWD for deploy."
                diag_dump; exit 1
              fi
              SUDO='sudo -n'
              run_sudo() { $SUDO "$@"; }
            fi

            # ---------- ensure dirs ----------
            mkdir -p "$BACKEND_DIR" "$FRONTEND_DIR"

            # ---------- NVM bootstrap (install Node if missing) ----------
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || true
            if ! command -v node >/dev/null 2>&1; then
              echo "Node not found; installing Node 22 via NVM..."
              [ -s "$NVM_DIR/nvm.sh" ] || { echo "ERROR: NVM not found at $NVM_DIR"; diag_dump; exit 1; }
              nvm install 22
            fi
            nvm use 22 >/dev/null 2>&1 || true
            log "Node: $(node -v), npm: $(npm -v)"

            # ---------- fresh shallow clone then mirror ----------
            TMPDIR="$(mktemp -d)"
            log "Cloning $REPO_URL branch $BRANCH → $TMPDIR/repo"
            git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$TMPDIR/repo"

            log "Sync backend sources → $BACKEND_DIR"
            rsync -a --delete --exclude ".git" "$TMPDIR/repo/backend/" "$BACKEND_DIR/"

            log "Build backend"
            cd "$BACKEND_DIR"
            npm ci
            npm run build

            # ---------- write/refresh systemd override ----------
            OV_DIR="/etc/systemd/system/explorertoken-backend.service.d"
            run_sudo mkdir -p "$OV_DIR"
            run_sudo tee "$OV_DIR/override.conf" >/dev/null <<EOF
[Service]
User=deploy
WorkingDirectory=$BACKEND_DIR
Environment=NODE_ENV=production
Environment=PATH=$(dirname "$NODE_BIN"):/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=
ExecStart=$NODE_BIN $ENTRYPOINT
Restart=always
RestartSec=3
EOF

            log "daemon-reload"
            run_sudo /usr/bin/systemctl daemon-reload

            log "Restart backend"
            if ! run_sudo /usr/bin/systemctl restart explorertoken-backend; then
              echo "ERROR: systemctl restart failed"
              diag_dump; exit 1
            fi

            log "Health check"
            if ! curl -fsS http://127.0.0.1:4000/health >/dev/null; then
              echo "ERROR: /health did not return 200"
              diag_dump; exit 1
            fi

            # ---------- frontend sync & build ----------
            log "Sync frontend sources → $FRONTEND_DIR"
            rsync -a --delete --exclude ".git" "$TMPDIR/repo/frontend/" "$FRONTEND_DIR/"

            log "Build frontend"
            cd "$FRONTEND_DIR"
            npm ci
            npm run build

            # ---------- publish frontend (domain-agnostic) ----------
            if [ -z "${PUBLISH_DIR:-}" ]; then
              PUBLISH_DIR="/var/www/html"
            fi
            log "Publish dist → $PUBLISH_DIR"
            run_sudo mkdir -p "$PUBLISH_DIR"
            run_sudo /usr/bin/rsync -a --delete dist/ "$PUBLISH_DIR"/

            # nginx sanity (no-op if absent)
            if command -v nginx >/dev/null 2>&1; then
              if run_sudo /usr/sbin/nginx -t; then
                run_sudo /usr/bin/systemctl reload nginx || true
              fi
            fi

            echo "Deploy completed"
