name: Deploy to VPS
on:
  workflow_dispatch:
    inputs:
      env:
        description: "GitHub Environment"
        required: true
        default: production
      branch:
        description: "Branch to deploy"
        required: true
        default: main

env:
  REPO_URL: https://github.com/WickedBroX/Blockchain.git
  BACKEND_DIR: /home/deploy/ExplorerToken/backend
  FRONTEND_DIR: /home/deploy/ExplorerToken/frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Assert required secrets
        shell: bash
        env:
          SSH_HOST:_
