name: Deploy to VPS

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment that holds SSH_* secrets"
        default: production
        required: true
        type: string
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env || 'production' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assert SSH secrets exist
        run: |
          test -n "${{ secrets.SSH_PRIVATE_KEY }}" || (echo "MISSING: SSH_PRIVATE_KEY" && exit 1)
          test -n "${{ secrets.SSH_HOST }}"        || (echo "MISSING: SSH_HOST" && exit 1)
          test -n "${{ secrets.SSH_USER }}"        || (echo "MISSING: SSH_USER" && exit 1)
          test -n "${{ secrets.SSH_PORT }}"        || (echo "MISSING: SSH_PORT" && exit 1)

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust host
        run: |
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Backend deploy
        env:
          REPO: ${{ github.repository }}        # expanded on RUNNER (e.g. WickedBroX/Blockchain)
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          # SUDO_PW: ${{ secrets.SUDO_PASSWORD }}   # uncomment if using Option 2 (sudo -S)
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" <<EOF
          set -eo pipefail
          cd ~/ExplorerToken

          # point origin to repo via SSH; NOTE: \$REPO is expanded by runner before sending
          git remote set-url origin git@github.com:${REPO}.git || true
          git fetch --prune
          DEF=\$(git remote show origin | sed -n 's/.*HEAD branch: //p'); [ -z "\$DEF" ] && DEF=main
          git checkout -B "\$DEF"
          git reset --hard "origin/\$DEF"

          # nvm/npm in non-interactive shell
          export NVM_DIR="\$HOME/.nvm"
          [ -s "\$NVM_DIR/nvm.sh" ] && . "\$NVM_DIR/nvm.sh"
          command -v nvm >/dev/null 2>&1 && { nvm use --lts || nvm use 22 || true; }
          export PATH="\$HOME/.nvm/versions/node/v22.21.0/bin:\$PATH"
          node -v && npm -v

          cd backend
          npm ci
          npm run build

          # SUDO OPTION 1: passwordless sudo (recommended; add a sudoers entry)
          sudo systemctl restart explorertoken-backend

          # SUDO OPTION 2: sudo with password (uncomment below + set SUDO_PASSWORD secret)
          # sudo_pw() { echo "\$SUDO_PW" | sudo -S "\$@"; }
          # sudo_pw systemctl restart explorertoken-backend

          curl -sS http://127.0.0.1:4000/health || true
          EOF

      - name: Frontend deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          # SUDO_PW: ${{ secrets.SUDO_PASSWORD }}   # uncomment if using Option 2
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" <<'EOF'
          set -eo pipefail

          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          command -v nvm >/dev/null 2>&1 && { nvm use --lts || nvm use 22 || true; }
          export PATH="$HOME/.nvm/versions/node/v22.21.0/bin:$PATH"
          node -v && npm -v

          cd ~/ExplorerToken/frontend
          npm ci
          npm run build

          WEB_ROOT=$(
            sudo nginx -T 2>/dev/null | awk '
              /server_name[^\n]*haswork\.dev/ { ins=1 }
              ins && $1=="root" { gsub(";","",$2); print $2; exit }
              ins && /}/ { ins=0 }'
          )
          [ -n "$WEB_ROOT" ] || WEB_ROOT="/var/www/haswork.dev"

          # SUDO OPTION 1: passwordless sudo
          sudo rsync -av --delete dist/ "$WEB_ROOT"/
          sudo nginx -t
          sudo systemctl reload nginx

          # SUDO OPTION 2: with password
          # sudo_pw() { echo "$SUDO_PW" | sudo -S "$@"; }
          # sudo_pw rsync -av --delete dist/ "$WEB_ROOT"/
          # sudo_pw nginx -t
          # sudo_pw systemctl reload nginx
          EOF

      - name: Collect backend logs (artifact)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" \
            "sudo journalctl -u explorertoken-backend -n 300 --no-pager" > backend_logs.txt || true
          tar -czf logs.tgz backend_logs.txt

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: server-logs
          path: logs.tgz
