name: Diagnose Environment Secrets
on:
  workflow_dispatch:
    inputs:
      env:
        description: "GitHub Environment"
        required: true
        default: production
jobs:
  diag:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Check required secrets (presence only)
        shell: bash
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          set +u
          for k in SSH_HOST SSH_USER SSH_PRIVATE_KEY; do
            v="${!k-}"
            [ -n "$v" ] && echo "::notice title=$k::SET" || echo "::error title=$k::MISSING"
          done
