name: Diagnose Environment Secrets

on:
  workflow_dispatch:
    inputs:
      env:
        description: "GitHub Environment"
        required: true
        default: production

jobs:
  diag:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Check required secrets/vars (presence only)
        shell: bash
        env:
          # REQUIRED
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # OPTIONAL
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
          WEB_ROOT: ${{ vars.WEB_ROOT }}
        run: |
          set +u
          check () { local k="$1"; local v="${!k-}"; [ -n "$v" ] && echo "::notice title=$k::SET" || echo "::error title=$k::MISSING"; }

          echo "Diagnosing Environment: ${{ inputs.env }}"
          echo "Required:"
          check SSH_HOST
          check SSH_USER
          check SSH_PRIVATE_KEY

          echo "Optional:"
          check SUDO_PASSWORD
          check WEB_ROOT

          echo "Open this step’s logs to see which are SET/MISSING."
