name: Diagnose Environment Secrets

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment with SSH_* secrets"
        default: production
        required: true
        type: string

jobs:
  diag:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Check required and optional secrets
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
          WEB_ROOT: ${{ secrets.WEB_ROOT }}
        shell: bash
        run: |
          set -euo pipefail

          missing_required=0

          check_required() {
            local name="$1"
            local value="${!name-}"
            if [[ -n "$value" ]]; then
              echo "::notice title=${name}::Secret is present"
            else
              echo "::error title=${name}::Secret is MISSING"
              missing_required=1
            fi
          }

          check_optional() {
            local name="$1"
            local value="${!name-}"
            if [[ -n "$value" ]]; then
              echo "::notice title=${name}::Secret is present"
            else
              echo "::notice title=${name}::Secret not set (optional)"
            fi
          }

          check_required SSH_HOST
          check_required SSH_USER
          check_required SSH_PRIVATE_KEY

          check_optional SSH_PORT
          check_optional SUDO_PASSWORD
          check_optional WEB_ROOT

          if [[ "$missing_required" -ne 0 ]]; then
            exit 1
          fi

      - name: Reminder
        run: echo "Review the step logs above for detailed secret diagnostics."
