name: SSH Smoke

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment that contains SSH_* secrets"
        default: production
        required: true
        type: string

jobs:
  smoke:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}  # <-- must match Environment name in your repo settings
    steps:
      - name: Show environment
        run: echo "Using environment: ${{ inputs.env }}"

      - name: Assert SSH secrets exist (won't print contents)
        run: |
          test -n "${{ secrets.SSH_PRIVATE_KEY }}" || (echo "MISSING: SSH_PRIVATE_KEY" && exit 1)
          test -n "${{ secrets.SSH_HOST }}"        || (echo "MISSING: SSH_HOST" && exit 1)
          test -n "${{ secrets.SSH_USER }}"        || (echo "MISSING: SSH_USER" && exit 1)
          test -n "${{ secrets.SSH_PORT }}"        || (echo "MISSING: SSH_PORT" && exit 1)
          echo "All required secrets are present."

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${SSH_PORT:-22}" "$SSH_HOST" >> ~/.ssh/known_hosts
          echo "known_hosts updated for $SSH_HOST:${SSH_PORT:-22}"

      - name: SSH debug (vvv)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          set -x
          ssh -vvv -o StrictHostKeyChecking=yes -p "${SSH_PORT:-22}" \
            "$SSH_USER@$SSH_HOST" 'whoami && uname -a && echo SHELL=$SHELL && ls -la ~/ExplorerToken || true'
