name: SSH Smoke

on:
  workflow_dispatch:
    inputs:
      env:
        description: "GitHub Environment that holds SSH_* secrets"
        default: production
        required: true
        type: string

jobs:
  smoke:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}   # <-- must match the Environment where you added SSH_* secrets
    steps:
      - name: Print which environment we’re using
        run: echo "Using environment: ${{ inputs.env }}"

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          : "${SSH_PORT:=${{ secrets.SSH_PORT }}}"
          : "${SSH_HOST:=${{ secrets.SSH_HOST }}}"
          mkdir -p ~/.ssh
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts
          echo "known_hosts updated for $SSH_HOST:$SSH_PORT"

      - name: SSH debug (whoami, uname, ls)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          set -x
          PORT="${SSH_PORT:-22}"
          ssh -vvv -o StrictHostKeyChecking=yes -p "$PORT" "$SSH_USER@$SSH_HOST" '
            whoami
            uname -a
            echo SHELL=$SHELL
            ls -la ~/ExplorerToken || true
          '
