name: SSH Smoke

on:
  workflow_dispatch:
    inputs:
      env:
        description: "GitHub Environment"
        required: true
        default: production

jobs:
  smoke:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Assert environment bindings (presence only)
        shell: bash
        env:
          # REQUIRED
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # OPTIONAL
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          set +u
          missing_required=0
          check_required () { local k="$1"; local v="${!k-}"; [ -n "$v" ] && echo "::notice title=REQUIRED:$k::SET" || { echo "::error title=REQUIRED:$k::MISSING"; missing_required=1; }; }
          check_optional () { local k="$1"; local v="${!k-}"; [ -n "$v" ] && echo "::notice title=OPTIONAL:$k::SET" || echo "::notice title=OPTIONAL:$k::MISSING (ok)"; }

          echo "Asserting Environment: ${{ inputs.env }}"
          check_required SSH_HOST
          check_required SSH_USER
          check_required SSH_PRIVATE_KEY
          check_optional SSH_PORT

          [ "$missing_required" -eq 0 ] || { echo "Missing required secrets"; exit 1; }

      - name: SSH to VPS and list project dir
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT != '' && secrets.SSH_PORT || '22' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail
            echo "whoami => $(whoami)"
            echo "host => $(hostname)"
            ls -la ~/ExplorerToken || true
            echo "OK"
