name: Diagnose Environment Secrets

on:
  workflow_dispatch:
    inputs:
      env:
        description: "GitHub Environment"
        required: true
        default: production

jobs:
  diag:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Check required secrets/vars (presence only)
        shell: bash
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}             # optional
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}   # optional
          WEB_ROOT: ${{ vars.WEB_ROOT }}               # optional (ENV var)
        run: |
          check() { local k="$1"; local v="${!k-}"; [ -n "$v" ] && echo "::notice title=$k::SET" || echo "::error title=$k::MISSING"; }
          echo "Diagnosing Environment: ${{ inputs.env }}"
          echo "Required:"; check SSH_HOST; check SSH_USER; check SSH_PRIVATE_KEY
          echo "Optional:"; check SSH_PORT; check SUDO_PASSWORD; check WEB_ROOT
          echo "Open this step’s logs for which items are SET/MISSING."
